core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url

from core.views import IndexView, index_view, AboutView, UsersView, UserView, CreatePostView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create_post/', CreatePostView.as_view(), name='create_post'),
    path('about/', AboutView.as_view(), name='about'),
    # path('rrr/', FeedbackView.as_view(), name='feedback'),
    path('all-users/', UsersView.as_view(), name='all_users'),
    path('account/<int:pk>/', UserView.as_view(), name='user_detail'),
    # url('^(?P<username>[-\w]+)/$', IndexView.as_view())
]

one_more_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('core.urls', 'urlpatterns'), namespace='core'))
    # path('<str:username>/', IndexView.as_view(), name='index'),
    # url('^(?P<username>[-\w]+)/$', IndexView.as_view())
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

core/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.db.models.aggregates import Sum
from django.contrib.auth import get_user_model

from django.db.models.signals import pre_save
from django.dispatch import receiver

# class TestModel(models.Model):
#     test_field = models.CharField(max_length=10)
#     test_integer = models.IntegerField()


def folder_avatar(obj):
    return f'avatars/{obj.username}'


class MyUser(AbstractUser):
    avatar = models.ImageField(upload_to=folder_avatar)
    phone = models.CharField(max_length=11)


class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    published_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True


class PostManager(models.Manager):

    def all_posts_views_count(self):
        queryset = self.get_queryset()
        return queryset.aggregate(views_count=Sum('views_count'))['views_count']

    def get_published(self):
        queryset = self.get_queryset()
        return queryset.filter(published_at__isnull=False)


class Post(TimeStamp):
    text = models.TextField()
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    tags = models.ManyToManyField('core.Tag')
    category = models.ForeignKey('core.Category', on_delete=models.CASCADE)

    views_count = models.IntegerField(default=0)
    like_count = models.IntegerField(default=0)

    preview = models.ImageField(upload_to='post/preview')

    ololo = PostManager()

    # class Meta:
    #     ordering = ['title']

    def __str__(self):
        return f"{self.title} by {self.author}"

    def save(self, *args, **kwargs):
        # Before save
        # self.title = 'Haha! Evil signal logic!'
        super(Post, self).save(*args, **kwargs)
        # After save


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


# @receiver(pre_save, sender=Post)
# def post_save_handler(sender, instance, **kwargs):
#     instance.title = 'Haha! Evil signal logic!'

core/forms.py
from django import forms

from core.models import Category, Post, Tag


# def get_category_choices():
#     return [
#         (x.id, x.name) for x in Category.objects.all()
#     ]


# class CreatePostForm(forms.Form):
#
#     categories = (
#         (1, 'Travel'),
#         (2, 'Hangover'),
#         (3, 'Bali')
#     )
#
#     title = forms.CharField(required=True, max_length=255, min_length=3, label='Nazvanie posta')
#
#     text = forms.CharField(widget=forms.widgets.Textarea(
#         attrs={'cols': 20, 'rows': 10, 'qwe': 123}
#     ), label='Tekst posta')
#
#     tags = forms.CharField(label='Tegi cherez zapyatuyu')
#
#     category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label='Ne zadano')
#
#     def __init__(self, *args, **kwargs):
#         super(CreatePostForm, self).__init__(*args, **kwargs)
#         # self.fields['category'].choices = [
#         #     (x.id, x.name) for x in Category.objects.all()
#         # ]
#
#     # def clean(self):
#
#     def clean_title(self):
#         title = self.cleaned_data['title']
#         if 'a' in title:
#             raise forms.ValidationError('Ne nado tak!')
#         return title
#
#     def save(self, user):
#         post = Post.ololo.create(
#             title=self.cleaned_data['title'],
#             text=self.cleaned_data['text'],
#             category=self.cleaned_data['category'],
#             author=user,
#             views_count=100
#         )
#         tags = []
#         for tag in self.cleaned_data['tags'].split(','):
#             tags.append(
#                 Tag.objects.get_or_create(name=tag)[0]
#             )
#
#         post.tags.set(tags)

class CreatePostForm(forms.ModelForm):

    tags = forms.CharField()

    class Meta:
        model = Post
        fields = (
            'title', 'text', 'category', 'preview'
        )

        widgets = {
            'text': forms.widgets.Textarea(attrs={'cols': 20, 'rows': 10})
        }

        labels = {
            'title': 'Nazvanie posta'
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if 'a' in title:
            raise forms.ValidationError('Ne nado tak!')
        return title

    def save(self, user, commit=True):
        post = super(CreatePostForm, self).save(commit=False)
        post.author = user
        post.save()
        tags = []
        for tag in self.cleaned_data['tags'].split(','):
            tags.append(
                Tag.objects.get_or_create(name=tag)[0]
            )

        post.tags.set(tags)

core/views.py
from django.views.generic import TemplateView
from django.views.generic.base import View
from django.views.generic.edit import CreateView, FormView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.models import User
from django.shortcuts import render
# from core.forms import TestForm
from django.urls.base import reverse_lazy
from django.db.models.query_utils import Q
from django.db.models import F
from django.db.models.aggregates import Sum
from django.contrib.auth import get_user_model

from core.models import Post, Tag, Category

from core.forms import CreatePostForm
from django.shortcuts import redirect


def index_view(request):
    if request.method == 'GET':
        return render(request, 'index.html')
    elif request.method == 'POST':
        print('POST')


# class IndexView(CreateView):
#     template_name = 'index.html'
#     form_class = TestForm
#     success_url = '/'

class IndexView(View):

    def dispatch(self, request, *args, **kwargs):
        return super(IndexView, self).dispatch(request, *args, **kwargs)

    def get(self, request):
        # print(username)
        # request is self.request  # True
        # request.GET
        # user = User.objects.get(username='admin')
        # posts = Post.objects.filter(author=user)
        # posts = Post.objects.all().select_related(
        #     'author'
        # ).prefetch_related(
        #     'tags'
        # )

        # Post.objects.filter(author=user).update(
        #     title='Good plan!')

        # post = Post.objects.create(
        #     text='Trololo',
        #     title='Loki jokes',
        #     author=user,
        #     category_id=1
        # )

        # post = Post.objects.get(id=4)
        #
        # post.tags.add(Tag.objects.get(id=1))

        # for post in posts:
        #     print(post.tags.all())

        # post = Post.objects.get(id=1)
        # post.title = 'Yaba aba'
        # post.save()

        # posts = Post.objects.all().exclude(title='Good plan')

        # posts = Post.objects.all().first()

        # posts = Post.objects.all().order_by('title').first()

        # .....

        # posts = posts.filter(author=user)

        # posts = Post.objects.filter(author__email='loki@loki.com').select_related()
        # posts = Post.objects.filter(title__startswith='Good')
        # posts = Post.objects.filter(title__contains='PL')

        # posts = Post.objects.filter(title__istartswith='Good')
        # posts = Post.objects.filter(title__icontains='PL')
        # filters = Q()

        # filters.add(Q.OR, title__startswith='Good')

        # posts = Post.objects.filter(
        #     Q(title__startswith='Good') &
        #     Q(title__contains='pl') &
        #     ~Q(author__username='loki')
        # ).distinct()

        # posts = Post.objects.filter(
        #     title=F('author__username')
        # )

        # posts = Post.objects.filter(tags__name='сказочноебали')
        # for post in posts:
        #     print(post.id)
        # print(posts)
        # counts = 0
        # for post in Post.objects.all():
        #     counts += post.views_count

        # counts = Post.objects.using('default').aggregate(Sum('views_count'))

        # counts = Post.objects.using('default').all()
        # counts2 = Post.objects.using('posts').all()
        #
        # counts = counts | counts2

        # counts = {}
        # for post in Post.objects.all():
        #     if post.author.username in counts:
        #         counts[post.author.username] += post.views_count
        #     else:
        #         counts[post.author.username] = post.views_count

        # counts = User.objects.annotate(views_count=Sum('post__views_count')).values(
        #     'username', 'views_count'
        # )

        # counts = User.objects.using('default').annotate(views_count=Sum('post__views_count')).order_by(
        #     '-views_count'
        # ).filter(views_count__gt=10)
        # print(counts)
        posts = Post.ololo.all()
        context = {
            'first': 123,
            'second': 321,
            'posts': posts
        }
        return render(request, 'index.html', context=context)

    def post(self, request):
        # request.POST
        return render(request, 'index.html')


class AboutView(TemplateView):
    template_name = 'about.html'

    # def get(self, request, *args, **kwargs):
    #     pass
    #     # return
    #
    # def render_to_response(self, context, **response_kwargs):
    #     pass
    #
    # def get_context_data(self, **kwargs):
    #     pass


# class FeedbackView(FormView):
#     template_name = 'feedback.html'
#     form_class = TestForm
#     success_url = reverse_lazy('core:feedback')
#
#     def form_valid(self, form):
#         print('Valid')
#         # self.request
#         # self.kwargs
#         return super(FeedbackView, self).form_valid(form)
#
#     def form_invalid(self, form):
#         print('Invalid')
#         return super(FeedbackView, self).form_invalid(form)

#

# class FeedbackView(View):
#
#     def get(self, request):
#         context = {
#             'form': TestForm()
#         }
#         return render(request, 'feedback.html', context)
#
#     def post(self, request):
#         form = TestForm(data=request.POST, files=request.FILES)
#         if form.is_valid():
#             print('Valid')
#         else:
#             print('Invalid')
#
#         context = {
#             'form': form
#         }
#         return render(request, 'feedback.html', context)


class UsersView(ListView):
    queryset = get_user_model()
    template_name = 'all_users.html'
    paginate_by = 10

    # def get_queryset(self):
    #     pass


class UserView(DetailView):
    template_name = 'user_profile.html'
    model = get_user_model()
    # slug_url_kwarg = 'username'
    # slug_field = 'username'

    # def get_object(self, queryset=None):
    #     pass


class CreatePostView(TemplateView):
    template_name = 'create_post.html'

    def get_context_data(self, **kwargs):
        context = super(CreatePostView, self).get_context_data(**kwargs)
        context['form'] = CreatePostForm()
        return context

    def post(self, request):
        form = CreatePostForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save(request.user)
            return redirect('/')
        context = self.get_context_data()
        context['form'] = form
        return self.render_to_response(context)


# class CreatePostView(FormView):
#     template_name = 'create_post.html'
#     form_class = CreatePostForm
#     success_url = '/'
#
#     def form_valid(self, form):
#         form.save(self.request.user)
#         return super(CreatePostView, self).form_valid(form)

# class CreatePostView(CreateView):
#     model = Post
#     success_url = '/'
#     fields = '__all__'
#     template_name = 'create_post.html'

core/templates/about.html
{% extends "base.html" %}
{% load my_filters %}

{% block content %}
    {% nav 'about' %}
    <h1>ABOUT PAGE</h1>
{% endblock content %}

core/templates/all_users.html
<ul>
{% for user in object_list %}
    <li>{{user.username}} - {{user.email}}</li>
{% endfor %}
</ul>

core/templates/base.html
{% load bootstrap4 %}

<html>
<head>
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>



    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>

</html>

core/templates/create_post.html
{% extends 'base.html' %}
{% load my_filters %}

{% block content %}
<div class="container">
    {% nav 'home' %}
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <form method="post" enctype="multipart/form-data">{% csrf_token %}
                {{ form.as_p }}
                <p>
                    <input type="submit" class="btn btn-primary" value="Sozdat">
                </p>
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>

{% endblock content %}

core/templates/feedback.html
<form method="post">{% csrf_token %}
    <table>
        {{form}}
    </table>
    <button type="submit">Send</button>
</form>

core/templates/index.html
{% extends "base.html" %}
{% load my_filters static thumbnail %}

{% block content %}

<div class="container">
    {% nav 'home' %}
</div>

<!--<h1>{{ some_var|safe|default:"No such variable!" }}</h1>-->
<!--<h1>{% now 'd m Y' %}</h1>-->
<!--<h1>{{ user.username }}</h1>-->
<h1>{{ second|minus:first }}</h1>
<div class="row">
    <!--<div class="col-md-3" style="border: 1px solid red">-->
        <!--<form method="post">{% csrf_token %}-->

        <!--</form>-->
    <!--</div>-->
    <p>
        <img src="{% static 'img/barney.jpg' %}">
    </p>

    {% for post in posts %}
        {# {% if post.views_count > 0 %} #}
            <div class="col-md-3" style="border: 1px solid red">{{ post.title }}</div>
            <div class="col-md-3" style="border: 1px solid red">{{ post.text }}</div>
            <div class="col-md-3" style="border: 1px solid red">{{ post.author }}</div>
            <div class="col-md-3" style="border: 1px solid red">
                <p>
                    {% if post.preview %}
                        {% thumbnail post.preview "100x100" as im %}
                            <img src="{{ im.url }}">
                        {% endthumbnail %}
                    {% endif %}
                </p>
                <p>
                {% autoescape off %}
                    {% get_post_tags post %}
                {% endautoescape %}
                </p>
            </div>
        {#{% else %}#}
        {#    <div class="col-md-12" style="border: 1px solid red">Views To low</div>#}
        {#{% endif %}#}
    {% endfor %}
</div>
{% endblock content %}

core/templates/nav.html
<div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% if selected == 'home' %}active{% endif %}">
            <a class="nav-link" href="{% url 'core:index' %}">Home {% if selected == 'home' %}<span class="sr-only">(current)</span>{% endif %}</a>
          </li>
          <li class="nav-item {% if selected == 'about' %}active{% endif %}">
            <a class="nav-link" href="{% url 'core:about' %}">About</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

core/templates/user_profile.html
User name: {{object.username}}<br>
User password: {{ object.password }}<br>
<br>
User email: {{ object.email }}<br>